#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$(dirname "$SCRIPT_DIR")")"
cd "$PROJECT_DIR"
if [ -d "../.venv/bin" ]; then
    source "../.venv/bin/activate"
fi
python -m alfredpy --gui
